### ISSUE TITLE
Merge / release async branch

### ISSUE THREAD

**Issue by thewtex** [fsspec/ipfsspec#9]
@d70-t the async branch looks great! :clap: :sparkle:  Any plans to merge / release?

**Comment by d70-t** [comment]
There's one major functionality missing in the async branch, and that's fallback between gateways, as I couldn't yet wrap my head around how to do that somehow properly in the async framework.

I'd love to merge and release, but the applications I know of often rely on "auto-configuration", which is currently implemented by balancing between potential gateways and peferring "good" ones for further requests.

It would be possible to merge the async branch anyways, but currently that branch uses `aipfs` as protocol identifier, so users could choose. But that's probably a bad idea in the long run, because that would lead to references using both `ipfs` and `aipfs` flying around in the wild.

My preferred path would be to implement this auto-failover on the async branch as well, but I current don't have too much time to do it. If you have any ideas on how that could be implemented, I'd be more than happy to hear about this.

**Comment by thewtex** [comment]
Yes, its does seem better to have one `ipfs` protocol going forward.

What do think about using the async backend by default, and enabling the synchronous through an environmental variable or package configuration variable?

For "auto-configuration", is trying a localhost gateway then falling back to one of the listed gateways sufficient? If localhost is used, there is libp2p's logic to use the swarm, the ability to configure known peers of interest. If an ipfs gateway on localhost is not available, the fallbacks can be tried. My impression is that the async implementation will give better performance over the synchronous implementation even if it picks an available gateway and sticks with it. Is that true?

**Comment by d70-t** [comment]
I'm not keen on having any synchronous backend. The only thing I really want, is that the library tries a reasonable amount of things to return requested content without any configuration. But probably, it's enugh to just try a few gateways. A few days ago, I found [aiohttp_retry](https://pypi.org/project/aiohttp-retry/) which besides providing various retry strategies for the same URL also implements a possibility to direct retries to different URLs. Probably this would be sufficient for a first release of the async branch.

**Comment by thewtex** [comment]
@d70-t thank you! :rocket:
